name: 'json_dynamic_widget_codegen_example'
description: 'A library to dynamically generate widgets within Flutter from JSON or other Map-like structures.'
homepage: 'https://github.com/peiffer-innovations/json_dynamic_widget'
version: '1.0.0'

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

analyzer:
  exclude:
    - 'lib/generated/**'
    - 'lib/**/*.g.dart'

dependencies:
  flutter:
    sdk: 'flutter'
  form_validation: '^3.1.0+1'
  json_dynamic_widget: '^6.0.6+2'
  json_dynamic_widget_annotations:
    path: ../../json_dynamic_widget_annotations
  json_theme: '^6.0.1+2'

dev_dependencies:
  build_runner: '^2.3.3'
  flutter_lints: '^2.0.1'
  flutter_test:
    sdk: 'flutter'
  # json_dynamic_widget_codegen: '^1.0.0'
  json_dynamic_widget_codegen:
    path: ../

dependency_overrides:
  json_dynamic_widget:
    path: ../../json_dynamic_widget
  json_dynamic_widget_annotations:
    path: ../../json_dynamic_widget_annotations
  json_theme:
    path: ../../json_theme/json_theme

ignore_updates:
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
