builders:
  widget_builder:
    import: 'package:json_dynamic_widget_codegen/builder.dart'
    builder_factories: ['widgetLibrary']
    build_extensions: { '.dart': ['widget.g.part'] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ['source_gen|combining_builder']
